### ISSUE TITLE
Cannot Launch Notes-Up

### ISSUE THREAD

**Issue by akasharora777** [Philip-Scott/Notes-up#166]
`$ notes-up 

** (Notes:6055): CRITICAL **: enotes_pages_list_load_pages: assertion 'notebook != NULL' failed
Segmentation fault (core dumped)
`

**Comment by Philip-Scott** [comment]
Are you use you're using the newest version? This should have been fixed already :) 

There's a `if (notebook == null) return;` in https://github.com/Philip-Scott/Notes-up/blob/0111ca47096b8d3a18866f28f21426f39e815a51/src/Widgets/PagesList.vala#L181

**Comment by akasharora777** [comment]
i actually got a work around it
saved the database 
purged and then re-installed it this time using the elementary OS's App Center
Current Version 1.3 

There is just a UI bug with the delete thing, rest is smooth
Anyway, great job with the application 
Really Loved It!

**Comment by Philip-Scott** [comment]
Where did you install it from before? And what UI bug? :)

**Comment by Philip-Scott** [comment]
Woops, i know what happened. Looks like you installed `notes-up` from my ppa instead of `com.github.philip-scott.notes-up` Both packages still exist in the old PPA, but the com... is the newest one. I've updated the readme with the new info :)

**Comment by akasharora777** [comment]
![notes-up](https://user-images.githubusercontent.com/20777462/29180315-0ef9b336-7e15-11e7-8598-0675ee3d00cf.png)  
UI Bug^^  
Deleted still shows until I quit and restart the application.

Yes, i added the ppa earlier.

**Comment by Philip-Scott** [comment]
Yeah, that's by design :) Things are only actually deleted once you close the app. 

Closing this report btw. Thank you for reporting the issue

**Comment by akasharora777** [comment]
Great Work! :)

**Comment by alchehabi** [comment]
I am on Juno up to date and I installed the app from appcenter, the app still doesn't launch in my computer.
after entering this command **com.github.philip-scott.notes-up** in terminal I receive the following:

[INFO 14:03:55.228934] Application.vala:155: Notes-Up version: 1.3
[INFO 14:03:55.228978] Application.vala:157: Kernel version: 4.15.0-42-generic
**
ERROR:/build/com.github.philip-scott.notes-up-1.6.2/src/Services/DatabaseTable.vala:73:database_table_prepare_db: assertion failed: (res == Sqlite.OK)
Aborted
